kind: pipeline
type: docker
name: app

steps:
  - name: linux amd64/386
    failure: ignore
    image: golang:1.22.2-alpine3.18
    commands:
      - cd /drone/src
      - cleartag="$(echo "${DRONE_TAG}" | sed -r 's/^.*?\b(v\d+(\.\d+)*).*$/\1/')"
      - env="$(echo "${DRONE_TAG}" | sed -r 's/^(\w+)-.+|.+-(\w+)$|.+/\1\2/')"
      - latest="$(test -n "$env" && echo "_$env" || echo "")"
      - envprint="$(test -n "$env" && echo "$env" || echo "prod")"
      - echo -e "\nEnv        → \e[32m$envprint\e[0m\nClear tag  → \e[36m$cleartag\e[0m\nLatest suf → \e[35m$latest\e[0m\n"
      - GOOS=linux GOARCH=amd64 go build -ldflags "-extldflags '-static' -X 'main.serviceVersion=${DRONE_TAG}' -X 'main.hashCommit=${DRONE_COMMIT}'" -o /opt/releases/app_linux_amd64_${DRONE_TAG} cmd/app/main.go
      - cp /opt/releases/app_linux_amd64_${DRONE_TAG} /opt/releases/app_linux_amd64$latest
      - cp /opt/releases/app_linux_amd64_${DRONE_TAG} /opt/releases/app_linux_386_${DRONE_TAG}
      - cp /opt/releases/app_linux_amd64_${DRONE_TAG} /opt/releases/app_linux_386$latest
    volumes:
      - name: releases
        path: /opt/releases
    when:
      event:
        - tag

# из-за неверного определения платформы для запуска нужной версии стартуем всегда 386, хотя надо 64
# временный фикс (создаем два файла для двух платформ но собранные для 64)
#  - name: linux 386
#    failure: ignore
#    image: golang:1.20.3-alpine3.17
#    commands:
#      - cd /drone/src
#      - GOOS=linux GOARCH=386 go build -ldflags "-extldflags '-static' -X 'main.serviceVersion=${DRONE_TAG}' -X 'main.hashCommit=${DRONE_COMMIT}'" -o /opt/releases/app_linux_386 cmd/app/main.go
#      - cp /opt/releases/app_linux_386 /opt/releases/app_linux_386_${DRONE_TAG}
#    volumes:
#      - name: releases
#        path: /opt/releases
#    when:
#      event:
#        - tag
  
  #  - name: darwin amd64
  #    failure: ignore
  #    image: golang:1.20.3-alpine3.17
  #    commands:
  #      - cd /drone/src
  #      - GOOS=darwin GOARCH=amd64 go build -ldflags "-extldflags '-static'" -o /opt/releases/app_darwin_amd64 cmd/app/main.go
  #      - cp /opt/releases/app_darwin_amd64 /opt/releases/app_darwin_amd64_${DRONE_TAG}
  #    volumes:
  #      - name: releases
  #        path: /opt/releases
  #    when:
  #      event:
  #        - tag

  - name: darwin arm64
    failure: ignore
    image: golang:1.22.2-alpine3.18
    commands:
      - cd /drone/src
      - cleartag="$(echo "${DRONE_TAG}" | sed -r 's/^.*?\b(v\d+(\.\d+)*).*$/\1/')"
      - env="$(echo "${DRONE_TAG}" | sed -r 's/^(\w+)-.+|.+-(\w+)$|.+/\1\2/')"
      - latest="$(test -n "$env" && echo "_$env" || echo "")"
      - envprint="$(test -n "$env" && echo "$env" || echo "prod")"
      - echo -e "\nEnv        → \e[32m$envprint\e[0m\nClear tag  → \e[36m$cleartag\e[0m\nLatest suf → \e[35m$latest\e[0m\n"
      - GOOS=darwin GOARCH=arm64 go build -ldflags "-extldflags '-static' -X 'main.serviceVersion=${DRONE_TAG}' -X 'main.hashCommit=${DRONE_COMMIT}'" -o /opt/releases/app_darwin_arm64_${DRONE_TAG} cmd/app/main.go
      - cp /opt/releases/app_darwin_arm64_${DRONE_TAG} /opt/releases/app_darwin_arm64$latest
    volumes:
      - name: releases
        path: /opt/releases
    when:
      event:
        - tag

volumes:
  - name: releases
    host:
      path: /opt/releases