// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by portals/wbswag at
// 2019-12-17 18:33:41.2333388 +0300 MSK m=+172.379991901

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/alive": {
            "get": {
                "description": "check application health",
                "produces": [
                    "text/plain"
                ],
                "summary": "alive",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/pass/forgot": {
            "post": {
                "summary": "issue reset iam",
                "parameters": [
                    {
                        "description": "pass forgot data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.PassForgotInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "initiator of operation",
                        "name": "X-Initiator-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/pass/reset": {
            "post": {
                "summary": "issue reset iam",
                "parameters": [
                    {
                        "description": "pass reset data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.PassResetInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user": {
            "post": {
                "summary": "create new user",
                "parameters": [
                    {
                        "description": "new user data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.UserForCreate"
                        }
                    },
                    {
                        "type": "string",
                        "description": "initiator of operation",
                        "name": "X-Initiator-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Response[models.ShortUser]"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/check": {
            "post": {
                "summary": "get user by login+pass pair",
                "parameters": [
                    {
                        "description": "login data",
                        "name": "login_input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.LoginPassInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Response[models.ShortUser]"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.Response[models.AttemptsOutput]"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/checksum/approve": {
            "post": {
                "summary": "approve password checksum",
                "parameters": [
                    {
                        "description": "password checksum data",
                        "name": "checksum_input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.CheckSumInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Response[models.CheckedOutput]"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.Response[responses.Params]"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/email/{email}": {
            "get": {
                "summary": "get users by email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user email",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Response[models.Users]"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/login/{login}": {
            "get": {
                "summary": "get users by email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user login",
                        "name": "login",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Response[models.ShortUser]"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/supplier/{id}": {
            "get": {
                "summary": "get users by supplier id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "supplier id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Response[models.Users]"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/{id}": {
            "get": {
                "summary": "get user data by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Response[models.ShortUser]"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            },
            "delete": {
                "summary": "delete user by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "initiator of operation",
                        "name": "X-Initiator-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            },
            "patch": {
                "summary": "update user data by id, except password",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "new users data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.ShortUser"
                        }
                    },
                    {
                        "type": "string",
                        "description": "initiator of operation",
                        "name": "X-Initiator-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Response[models.ShortUser]"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/{id}/changepass": {
            "post": {
                "summary": "change password of user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "change pass data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.ChangePassInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "initiator of operation",
                        "name": "X-Initiator-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/{id}/changepassunsafe": {
            "post": {
                "summary": "change password of user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "change pass data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.ChangePassUnsafeInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "initiator of operation",
                        "name": "X-Initiator-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AttemptsOutput": {
            "type": "object",
            "properties": {
                "bad_attempts": {
                    "type": "integer",
                    "example": 1
                },
                "period_minutes": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "models.ChangePassInput": {
            "type": "object",
            "properties": {
                "current_password": {
                    "type": "string",
                    "example": "Qwerty123"
                },
                "new_password": {
                    "type": "string",
                    "example": "Qwerty112233"
                }
            }
        },
        "models.ChangePassUnsafeInput": {
            "type": "object",
            "properties": {
                "new_password": {
                    "type": "string",
                    "example": "Qwerty112233"
                }
            }
        },
        "models.CheckSumInput": {
            "type": "object",
            "properties": {
                "checksum": {
                    "type": "string",
                    "example": "mWzulhSEIsdRfw8rYaPDiAS9dTFx96VuMd7pAKzo4MM="
                },
                "login": {
                    "type": "string",
                    "example": "Tolkacheva.Elena@wildberries.ru"
                }
            }
        },
        "models.CheckedOutput": {
            "type": "object",
            "properties": {
                "checked": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.LoginPassInput": {
            "type": "object",
            "properties": {
                "login": {
                    "description": "login OR email",
                    "type": "string",
                    "example": "Tolkacheva.Elena@wildberries.ru"
                },
                "password": {
                    "type": "string",
                    "example": "qwerty"
                },
                "period_minutes": {
                    "description": "bad attempts count during this period in minutes",
                    "type": "integer",
                    "default": 10,
                    "example": 15
                }
            }
        },
        "models.PassForgotInput": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "template_id": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.PassResetInput": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "template_id": {
                    "type": "string"
                },
                "iam": {
                    "type": "string"
                }
            }
        },
        "models.ShortUser": {
            "type": "object",
            "properties": {
                "checksum": {
                    "type": "string",
                    "example": "2L7xhnV9qw/witp9iPdXmKEG14Ea5qbjvgsXruGGO5I="
                },
                "created": {
                    "type": "string",
                    "example": "2019-05-21T12:41:04+03:00"
                },
                "email": {
                    "type": "string",
                    "example": "Tolkacheva.Elena@wildberries.ru"
                },
                "full_name": {
                    "type": "string"
                },
                "lang": {
                    "type": "string"
                },
                "login": {
                    "type": "string",
                    "example": "supp374836"
                },
                "supplier_id": {
                    "type": "integer",
                    "example": 8759
                },
                "user_id": {
                    "type": "integer",
                    "example": 374836
                }
            }
        },
        "models.UserForCreate": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "Tolkacheva.Elena@wildberries.ru"
                },
                "full_name": {
                    "type": "string",
                    "example": "Иванов Иван Иванович"
                },
                "lang": {
                    "type": "string",
                    "example": "en"
                },
                "login": {
                    "type": "string",
                    "example": "mylogin"
                },
                "password": {
                    "type": "string",
                    "example": "Qwerty112233"
                },
                "supplier_id": {
                    "type": "integer",
                    "example": 8759
                }
            }
        },
        "models.Users": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "checksum": {
                        "type": "string",
                        "example": "2L7xhnV9qw/witp9iPdXmKEG14Ea5qbjvgsXruGGO5I="
                    },
                    "created": {
                        "type": "string",
                        "example": "2019-05-21T12:41:04+03:00"
                    },
                    "email": {
                        "type": "string",
                        "example": "Tolkacheva.Elena@wildberries.ru"
                    },
                    "full_name": {
                        "type": "string"
                    },
                    "lang": {
                        "type": "string"
                    },
                    "login": {
                        "type": "string",
                        "example": "supp374836"
                    },
                    "supplier_id": {
                        "type": "integer",
                        "example": 8759
                    },
                    "user_id": {
                        "type": "integer",
                        "example": 374836
                    }
                }
            }
        },
        "responses.Param": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "login"
                },
                "reason": {
                    "type": "string",
                    "example": "login reqired"
                }
            }
        },
        "responses.Params": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "example": "login"
                    },
                    "reason": {
                        "type": "string",
                        "example": "login reqired"
                    }
                }
            }
        },
        "responses.Response": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "validation error"
                },
                "result": {
                    "type": "object"
                },
                "title": {
                    "type": "string",
                    "example": "Ошибка запроса"
                },
                "type": {
                    "type": "string",
                    "example": "business/error"
                },
                "version": {
                    "type": "string",
                    "example": "1.0"
                }
            }
        },
        "responses.Response[models.AttemptsOutput]": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "validation error"
                },
                "result": {
                    "type": "object",
                    "properties": {
                        "bad_attempts": {
                            "type": "integer",
                            "example": 1
                        },
                        "period_minutes": {
                            "type": "integer",
                            "example": 10
                        }
                    }
                },
                "title": {
                    "type": "string",
                    "example": "Ошибка запроса"
                },
                "type": {
                    "type": "string",
                    "example": "business/error"
                },
                "version": {
                    "type": "string",
                    "example": "1.0"
                }
            }
        },
        "responses.Response[models.CheckedOutput]": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "validation error"
                },
                "result": {
                    "type": "object",
                    "properties": {
                        "checked": {
                            "type": "boolean",
                            "example": true
                        }
                    }
                },
                "title": {
                    "type": "string",
                    "example": "Ошибка запроса"
                },
                "type": {
                    "type": "string",
                    "example": "business/error"
                },
                "version": {
                    "type": "string",
                    "example": "1.0"
                }
            }
        },
        "responses.Response[models.ShortUser]": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "validation error"
                },
                "result": {
                    "type": "object",
                    "properties": {
                        "checksum": {
                            "type": "string",
                            "example": "2L7xhnV9qw/witp9iPdXmKEG14Ea5qbjvgsXruGGO5I="
                        },
                        "created": {
                            "type": "string",
                            "example": "2019-05-21T12:41:04+03:00"
                        },
                        "email": {
                            "type": "string",
                            "example": "Tolkacheva.Elena@wildberries.ru"
                        },
                        "login": {
                            "type": "string",
                            "example": "supp374836"
                        },
                        "supplier_id": {
                            "type": "integer",
                            "example": 8759
                        },
                        "user_id": {
                            "type": "integer",
                            "example": 374836
                        }
                    }
                },
                "title": {
                    "type": "string",
                    "example": "Ошибка запроса"
                },
                "type": {
                    "type": "string",
                    "example": "business/error"
                },
                "version": {
                    "type": "string",
                    "example": "1.0"
                }
            }
        },
        "responses.Response[models.Users]": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "validation error"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ShortUser"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "Ошибка запроса"
                },
                "type": {
                    "type": "string",
                    "example": "business/error"
                },
                "version": {
                    "type": "string",
                    "example": "1.0"
                }
            }
        },
        "responses.Response[responses.Params]": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "validation error"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.Param"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "Ошибка запроса"
                },
                "type": {
                    "type": "string",
                    "example": "business/error"
                },
                "version": {
                    "type": "string",
                    "example": "1.0"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-App-Key",
            "in": "header"
        }
    },
    "security": [
        {
            "ApiKeyAuth": []
        }
    ]
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.1",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{"https"},
	Title:       "PORTAL User Identity API",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
